- name: install filesystem utilities - Archlinux
  pacman:
    name:
    - fuse
    - tree
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install filesystem utilities - Debian
  apt:
    name:
    - fuse
    - tree
    state: present
  when: ansible_facts['distribution'] == 'Debian'
