- name: install xorg-server - Archlinux
  pacman:
    name:
      - xorg-server
      - xf86-video-vmware
      - xorg-apps
      - xorg-xinit
      - xterm
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install xorg-server
  apt:
    name:
      - xserver-xorg
      - xserver-xorg-video-vmware
      - xinit
      - xterm
    state: present
  when: ansible_facts['distribution'] == 'Debian'
