- name: install openssh - Archlinux
  pacman:
    name: openssh
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install openssh - Debian
  apt:
    name: openssh-client
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: create ssh config dir
  file:
    path: '/home/{{ user }}/.ssh'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ group }}'

- name: configure ssh client
  template:
    src: config
    dest: '/home/{{ user }}/.ssh/config'
    mode: 0400
    owner: '{{ user }}'
    group: '{{ group }}'
