- name: install openssh
  pacman:
    name: openssh
    state: present

- name: create ssh config dir
  file:
    path: '/home/{{ user }}/.ssh'
    state: directory
    mode: 0700
    owner: '{{ user }}'
    group: '{{ group }}'

- name: configure ssh client
  template:
    src: config
    dest: '/home/{{ user }}/.ssh/config'
    mode: 0400
    owner: '{{ user }}'
    group: '{{ group }}'
