- name: install podman and dependencies
  pacman:
    name:
      - podman
      - podman-compose
      - aardvark-dns
    state: present

- name: configure podman
  copy:
    src: registries.conf
    dest: /etc/containers/registries.conf
    mode: 0444
    owner: root
    group: root

- name: configure podman environment
  template:
    src: 01-podman.env
    dest: '/home/{{ user }}/.profile.d/01-podman.env'
    mode: 0400
    owner: '{{ user }}'
    group: '{{ group }}'
