- name: install git - Archlinux
  pacman:
    name: git
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install git - Debian
  apt:
    name: git
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: configure git
  copy:
    src: gitconfig
    dest: '/home/{{ user }}/.gitconfig'
    mode: 0400
    owner: '{{ user }}'
    group: '{{ group }}'
