- name: update pacman cache
  pacman:
    update_cache: yes
  when: ansible_facts['distribution'] == 'Archlinux'

- name: update apt cache
  apt:
    update_cache: yes
  when: ansible_facts['distribution'] == 'Debian'
