- name: install sudo - Archlinux
  pacman:
    name: sudo
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install sudo - Debian
  apt:
    name: sudo
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: configure sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: 0400
    owner: root
    group: root

- name: create /etc/sudoers.d
  file:
    dest: /etc/sudoers.d
    mode: 0500
    owner: root
    group: root
    state: directory
