- name: install needed development packages - Archlinux
  pacman:
    name:
      - cmake
      - base-devel
      - fakeroot
      - man
      - pkgconf
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install needed development packages - Debian
  apt:
    name:
      - cmake
      - build-essential
      - fakeroot
      - man
      - pkgconf
    state: present
  when: ansible_facts['distribution'] == 'Debian'
