- name: install haskell development tools - Archlinux
  pacman:
    name:
      - ghc
      - cabal-install
      - stack
      - haskell-language-server
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install haskell development tools - Debian
  apt:
    name:
      - ghc
      - cabal-install
      - haskell-stack
    state: present
  when: ansible_facts['distribution'] == 'Debian'
