- name: install tmux
  pacman:
    name: tmux
    state: present

- name: install xclip
  pacman:
    name: xclip
    state: present

- name: configure tmux
  copy:
    src: tmux.conf
    dest: '/home/{{ user }}/.tmux.conf'
    mode: 0400
    owner: '{{ user }}'
    group: '{{ group }}'

- name: create ,devmux script
  copy:
    src: ',devmux'
    dest: '/home/{{ user }}/scripts/,devmux'
    mode: 0500
    owner: '{{ user }}'
    group: '{{ group }}'
