- name: install tmux - Archlinux
  pacman:
    name:
      - tmux
      - xclip
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install tmux - Debian
  apt:
    name:
      - tmux
      - xclip
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: configure tmux
  copy:
    src: tmux.conf
    dest: '/home/{{ user }}/.tmux.conf'
    mode: 0400
    owner: '{{ user }}'
    group: '{{ group }}'

- name: create ,devmux script
  copy:
    src: ',devmux'
    dest: '/home/{{ user }}/scripts/,devmux'
    mode: 0500
    owner: '{{ user }}'
    group: '{{ group }}'
