- name: install lightdm - Archlinux
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: install lightdm - Debian
  apt:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: enable lightdm service
  service:
    name: lightdm.service
    enabled: true
